name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/web-push-demo:latest .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/web-push-demo:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.6.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Test SSH connection
        run: |
          ssh -o StrictHostKeyChecking=no -v ${{ secrets.VPS_ACCESS }} exit

      - name: SSH into VPS and run Docker container
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_ACCESS }} << 'EOF'
            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/my-image:latest
            docker stop web-push-demo || true
            docker rm web-push-demo || true
            docker run -d --name web-push-demo ${{ secrets.DOCKER_HUB_USERNAME }}/web-push-demo:latest
          EOF
