name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  # Optionally, trigger this workflow on tag creation
  # tags:
  #   - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build Docker image
        run: docker build -t my-image:latest .

      - name: Push Docker image
        run: docker push my-image:latest
