name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: yarn

      - name: Lint
        run: yarn lint

      - name: Build packages
        run: yarn build

      - name: Tests
        run: yarn test

  build:
    runs-on: ubuntu-latest
    needs: checks

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/web-push-demo:latest .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/web-push-demo:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.6.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Test SSH connection
        run: |
          ssh -o StrictHostKeyChecking=no -v ${{ secrets.VPS_ACCESS }} exit

      - name: SSH into VPS and run Docker container
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_ACCESS }} << 'EOF'
            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/web-push-demo:latest
            docker stop web-push-demo || true
            docker rm web-push-demo || true
            docker ps -a -q -f status=exited | xargs --no-run-if-empty docker rm -v || true
            docker images -f "dangling=true" -q | xargs --no-run-if-empty docker rmi || true
            docker images | awk '/ago/  { print $3}' | xargs --no-run-if-empty docker rmi || true
            docker volume ls -qf dangling=true | xargs --no-run-if-empty docker volume rm || true
            docker run -d \
              --name web-push-demo \
              -p 3000:3000 \
              -p 7777:8888 \
              -e VAPID_PUBLIC_KEY=${{secrets.VAPID_PUBLIC_KEY}} \
              -e VAPID_PRIVATE_KEY=${{secrets.VAPID_PRIVATE_KEY}} \
              ${{ secrets.DOCKER_HUB_USERNAME }}/web-push-demo:latest \
              yarn start
          EOF
